### PR TITLE
Adding sorting methods to collections

### PR DESCRIPTION
**Pull request by matifreyre**
Feature #510: Should be a way to have an ordered list
Adding sortBy to List (side-effect version) and sortedBy to Collection (no side-effect version: returns a new List).
Please let me know everything you see that can be improved.

### CODE REVIEW

**Comment by matifreyre** [comment]
Those tests run smoothly on eclipse. I'm not sure what's making them fail here.

**Comment by javierfernandes** [comment]
The build in travis was failing due to some sort of transient error related to network connections to maven repo's or something.
It now ran but I got some errors in ListTestCase. The new tests include "val" keyword which should now be "const".
I'm changing that.

**Comment by javierfernandes** [comment]
ListTest seems to fail randomly (the push build succeded by the PR build failed)

**Comment by javierfernandes** [comment]
Ran fine locally. Let's cross fingers

**Pull request merged**
