### PR TITLE
Type system

### PR DESCRIPTION
**Pull request by npasserini**

### CODE REVIEW

**Comment by npasserini** [comment]
image

**Comment by fdodino** [comment]
Wow!

Can I use it for Static Diagram also?
Will take a look if you can wait until Monday or Tuesday...

**Comment by npasserini** [comment]
It is very primitive yet, but I hope you will be able to use it soon.

2017-05-26 12:10 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
Using substitution type system, I got a nice validation error:
:smile:

image

**Comment by fdodino** [comment]
Also working in Outline view!

image

I was seeing methods pointing to empty string before... or Any as type variables

**Comment by tesonep** [comment]
@npasserini what I do with the branch, you want to keep it or I delete it??

**Comment by npasserini** [comment]
@tesonep I would keep it, we can continue working there.
@fdodino We are working on Constraint Based type system


2017-05-29 11:17 GMT-03:00 Pablo Tesone <notifications@github.com>:

**Pull request merged**
