### PR TITLE
Repl #790 rtf copy

### PR DESCRIPTION
**Pull request by fdodino**
Finally, I got it.
Now you can copy in the REPL & paste in Word, Office Writer and any RTF document.

### CODE REVIEW

**Comment by fdodino** [comment]
Oh, by the way, there are many CHANGELOG.md & changelog.txt, I suppose that is because I run a mvn clean install. They bother me, because it is difficult to see the changes, @tesonep @javierfernandes should I delete them? I thought there were part of the build, so I didn't remove them.

**Comment by javierfernandes** [comment]
Right. Seems like maven should only generate this while releasing and also just one for the parent project, and not a file for each module :S

**Comment by javierfernandes** [comment]
As Carlitos would say: "it is very difficult" to see the PR with all the changelogs. Github doesn't show them to me.
Can you see if you can delete the changelog files and commit ?

**Comment by fdodino** [comment]
Ok, my Unix old days were back

```
# find * -print | grep changelog.txt | rm $1
```

just in case you need it.

**Comment by fdodino** [comment]
travis

**Comment by javierfernandes** [comment]
jajaja !!!

just in case an improvement to the command

find . -name changelog.txt | xargs rm -f


find . -name CHANGELOG.md | xargs rm -f

**Pull request merged**
