### PR TITLE
Fix 1346 constructor call constraints

### PR DESCRIPTION
**Pull request by npasserini**
I understand that this covers all "traditional" constructors, both in the directly reference class and inherited. I used the look up strategy already present (`resolveConstructor`). @fdodino please verify my logic.

We should create another issue / pr for automatic (name-based) initialization which is not considered anywhere in TS.

### CODE REVIEW

**Comment by fdodino** [comment]
I changed the base from master to dev-1.6, I don't know if I have to do a rebuild from travis...

**Comment by npasserini** [comment]
@fdodino any comments on this? Do we merge?

**Comment by fdodino** [comment]
Please let me 2 hours and I'll see it...

**Comment by fdodino** [comment]
Perfect! Let's merge it!

**Pull request merged**
