### PR TITLE
Removing unused messages

### PR DESCRIPTION
**Pull request by tesonep**
Fixes issue #608

### CODE REVIEW

**Comment by javierfernandes** [comment]
I think this messages are being used. Because the validator's section in the configuration is now being show into "sections" to group similar rules together.
Probably just the comment got outdated, right ?

Also in the commit I see that you added them, not removed, right ?

**Comment by tesonep** [comment]
I have check if the messages are used, but they are not. They were in the properties but not in the Java side. I comment them because maybe they are used.

**Comment by javierfernandes** [comment]
There are some cases where we use reflection to resolve properties :P
This was to build like a more declarative mini-fwk for validations with configurations

Here is the annotation used to declare that a given validator method belongs to a group

https://github.com/uqbar-project/wollok/blob/master/org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokCheckGroup.xtend

Here is a sample validator for "code style"
https://github.com/uqbar-project/wollok/blob/master/org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend#L117

Somewhere, I supposed in the "ui" part there's the preference pages shows the list of checkboxes grouped in panels based on these groups and uses the i18n for showing their names.

**Comment by javierfernandes** [comment]
Ok, here is the issue with a screen shot

https://github.com/uqbar-project/wollok/issues/335

And the line where it resolves the group name in i18n based on a convention

https://github.com/uqbar-project/wollok/commit/2e304df9ddb6e5e2ef796d6f90f3a8683dc5f42e#diff-110562837e0fe4917f38d4c9c2092fccR74

So, seems like it is used

**Comment by tesonep** [comment]
I put back the messages, but I have added the entry in the Java side so the warning goes away. It seems this thing of the PR and reviewing the code is working, these hippies are right.

**Comment by javierfernandes** [comment]
👍

**Comment by javierfernandes** [comment]
Should we merge this ?
Was 1.4.3 released already ?

**Comment by tesonep** [comment]
Yes, the idea is to integrate these changes in 1.4.3 and then in 1.5.0. The 1.4.3 is still open.

**Pull request merged**
