### PR TITLE
Gitignore xsemantics

### PR DESCRIPTION
**Pull request by mmatos**
Generated files should not be tracked. Removing xsemantics-gen from typesystem tracking

### CODE REVIEW

**Comment by mmatos** [comment]
Apparently it is not possible to delete this file at the moment because of Travis build process.

**Comment by npasserini** [comment]
This should not be done as there is a problem in travis that prevents builds from finishing if we do not commit this files. Please confirm @tesonep.

**Comment by tesonep** [comment]
To me it is better not to do it. I have fighted a lot with this. Close it
and forget.

On 16 Sep 2017 18:25, "Nico Passerini" <notifications@github.com> wrote:

Closed #1098 <https://github.com/uqbar-project/wollok/pull/1098>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/uqbar-project/wollok/pull/1098#event-1252209295>, or mute
the thread

**Comment by npasserini** [comment]
I already closed it. I think this will be solved when/if we discard
xsemantics. We're not far from that.

2017-09-18 8:49 GMT-03:00 Pablo Tesone <notifications@github.com>:

> To me it is better not to do it. I have fighted a lot with this. Close it
> and forget.
>

**Pull request closed without merging**
