### PR TITLE
New default image for visuals

### PR DESCRIPTION
**Pull request by PalumboN**
Close https://github.com/uqbar-project/wollok/issues/898
Close https://github.com/uqbar-project/wollok/issues/899

When you don't declare an image:
default_image

And when you declare an image and it hasn't found:
not_found_image

### CODE REVIEW

**Comment by javierfernandes** [comment]
Nice !
I'm afraid that using the wollok icon as it is makes it difficult to read. Since it has a transparency in the W.

Can you check this one ?
I'm not completely satisfied with it. But I was not able to make it more readable. Maybe if we use the other icon.

wgame-image-not-found

**Comment by PalumboN** [comment]
Cool! Yeah I thought the same. But the text is added dynamically (it's not in the image), so I can use the same icon for both cases.

Do you have only the icon with white background?

**Comment by javierfernandes** [comment]
wgame-image-not-found

Here !

**Comment by PalumboN** [comment]
Done!
screenshot from 2016-08-10 23 03 30

What do you think now, @javierfernandes?

**Comment by javierfernandes** [comment]
Cool ! sorry for the delay. I missed your last comment :S

**Pull request merged**
