### PR TITLE
#603 Fix for variable scope of NamedObject

### PR DESCRIPTION
**Pull request by mmatos**
For the moment, I only changed scope(WNamedObject namedObject) to consider the parent's scope as well. I didn't include mixins because I wasn't sure about what was expected on that aspect (not sure if NamedObjects will be expected to be mixed in in the future).

All preexistent test cases pass and the additioned objectInheritFromCustomClassWithInstanceVariable test case in NamedObjectInheritanceTest is also green after the fix.

In an unrelated topic, after I made the change I noticed that the following files were also updated and git prompted me to include them in the commit, but I think they just need to be ignored and not commited (they are listed in .gitignore files under org.uqbar.project.wollok.typeSystem.xsemantics\xsemantics-gen\org\uqbar\project\wollok\semantics):
/.WollokDslTypeSystem.java._trace
/.WollokDslTypeSystemValidator.java._trace

Please advice in case I need to do something about that.

### CODE REVIEW

**Comment by javierfernandes** [comment]
Yes. trace files are generated by xtend compiler.
We don't need to version them. Maybe we did it already, then we should clean up.

Regarding your change. It seems fine.
Just that, WKO already support mixins, and they are currently being taking into account for the scope of WClass (classes), so WKO are more close to be consistent with classes with your change, but not 100%.

Do you mind also adding the mixins scope ?
At least we will have something 100% consistent.
Then we can discuss to change the scoping as we want.

Agree ?

**Comment by mmatos** [comment]
Yes, I agree, just wanted to confirm first

**Comment by mmatos** [comment]
I added the change to consider also mixins and a test case to validate it works as expected, though there is duplicated code.

Looking at WNamedObject and WClass I see that they both define getParent and getMixins independently, so maybe those declarations could be in WCanExtendClass so a single definition for scope can be done for WCanExtendClass?

**Comment by javierfernandes** [comment]
Cool!

So, regarding the duplication, you are right.
It's a usual problem with xtext that is not easily to solve, at least not
in the way we would like.
As all this classes like WNamedObject and WClass, are generated based on
the grammar (WollokDsl.xtext),
we don't have full control on them.
XText does a pretty good job on abstracting superclasses and interfaces,
and moving up some fields/methods
but sometimes it doesn't, like in this case.
And we end up with two classes defining the same thing.

One way to overcome that and make them polymorphic is to use extension
methods and multiple dispatch
for example:


def dispatch getTheMixins(WClass c) { return c.mixins }
def dispatch getTheMixins(WNamedObject wko) { return wko.mixins }


Then you can do x.getTheMixins() in both WClass and WNamedObject.

I believe I already wrote this methods in one of our "extension classes".
Look for W*Extension. Like WMethodContainerExtensions, etc. (we could
better organize this extensions, we have a lot).

Anyway, I think we are good for the PR right now.
If you want to refactor this later we can do another.

Thanks !

**Pull request merged**
