### PR TITLE
Formatter issues

### PR DESCRIPTION
**Pull request by fdodino**
It is still a work in progress, but I want to make some checks for travis builds.

### CODE REVIEW

**Comment by fdodino** [comment]
Well, I will do some additional tests, but I think I got it @tesonep 

Issues addressed:

#702 
#404 
#687 
#1201 
#696 
#188 

I added a new line surrounding method containers.

**Comment by tesonep** [comment]
@fdodino this is open? cause it seems nice....

**Comment by fdodino** [comment]
I am pulling UTN students repos, to format their files and see if there are still conflicts between grammars. Just a few more hours. The good part is that I learn how are students programming style....

**Comment by tesonep** [comment]
@fdodino and are you taking your eyeballs out with a fork??

**Comment by fdodino** [comment]
Hahaha!! There are good surprises too, and in each milestone there is always a teacher correcting bad habits personally.

**Comment by fdodino** [comment]
Ready, set, go!

**Pull request merged**
