### PR TITLE
Feature #409 haskellize collections messages

### LINKED ISSUE #409: Use collection messages consistent with Haskell's Prelude
The following collection messages are inconsistent with Haskell's Prelude

* `detect` -> `find`
* `exists` -> `any`
* `forAll` -> `all`

### PR DESCRIPTION
**Pull request by flbulgarelli**
Fixes #409

### CODE REVIEW

**Comment by javierfernandes** [comment]
oops.. I think that we need to re-do this because we have completely changed the way lists are implemented in this branch https://github.com/uqbar-project/wollok/tree/dev-natives-to-wollok

We will be merging that branch to dev pretty soon. 
There's a PR for that #376

Actually AbsctractCollection has been completely removed

**Comment by flbulgarelli** [comment]
OK, So closing this by now.

**Comment by javierfernandes** [comment]
Can we delete this branch ? (cleaning up branches)

**Comment by npasserini** [comment]
I think that there already is another branch with this feature. So yes.

**Pull request closed without merging**
